### ISSUE TITLE
d3-install-dtb

### ISSUE THREAD

**Issue by qodlsrud20712** [D3Engineering/d3-jetson-bsp#15]
what is Select a valid d3 bsp kernel release?

**Comment by greg-rowe** [comment]
When you run `d3-install-dtb` you will first be presented with a menu of kernels that are installed on the filesystem. "Select a valid d3 bsp kernel release" means to choose, from that menu, a D3 kernel. Once that is chosen you will see a second menu with options for which .dtb file to install.

**Comment by D3-growe** [comment]
When you run `d3-install-dtb` you will first be presented with a menu of kernels that are installed on the filesystem. "Select a valid d3 bsp kernel release" means to choose, from that menu, a D3 kernel. Once that is chosen you will see a second menu with options for which .dtb file to install.

**Comment by qodlsrud20712** [comment]
thank you ,

2021년 7월 7일 (수) 오전 6:31, Greg Rowe ***@***.***>님이 작성:
