### ISSUE TITLE
Build ID mismatch 

### ISSUE THREAD

**Issue by D3-growe** [D3Engineering/d3-jetson-bsp#2]
In the 2.0.0 release the build ID for the DTB does not match the build ID for the kernel. The mismatch can safely be ignored. 

The build ID for the kernel is: 98dbeefb-81a9-44d2-ab75-65d02c784d1e. If /sys/module/build_id/version contains that build ID then the kernel has successfully been installed.

This problem has been corrected for our next release.

**Comment by D3-cwhite** [comment]
Can this be closed since 3.0.1 is out?
