### ISSUE TITLE
New jetpack releases

### ISSUE THREAD

**Issue by eliabruni** [D3Engineering/d3-jetson-bsp#20]
Hello,

Do you have an ETA for jetpack 4.5 and 4.6 releases?

Thank you!

**Comment by D3-growe** [comment]
Hello Elia,

D3 is actively working on updates for JetPack 4.6. Unfortunately I can't provide a specific time-frame.

Thanks,
Greg

**Comment by eliabruni** [comment]
Hello Greg,

Thanks for the prompt answer!
