### ISSUE TITLE
Is Jetson SERDES Sensor Interface card work with latest Jetpack 5.0.1 or 5.0.2

### ISSUE THREAD

**Issue by vivekJB1** [D3Engineering/d3-jetson-bsp#26]
Hi,
I have Jetson SERDES Sensor Interface card which can interface total of 6 cameras.

D3 Jetson BSP v5.0 release note state that this SERDES card work only with  NVIDIA JetPack 4.6.1.
Does is work with latest  NVIDIA JetPack  5.0.1 or 5.0.2?

**Comment by vivekJB1** [comment]
@D3-growe @D3-jwatts @d3-sdunnington

**Comment by d3-cburrows** [comment]
Hi vivekJB1,

Thanks for opening this issue. Unfortunately BSP 5.0.0 only works with JetPack 4.6.1. We are currently wrapping up development on a new release which supports JetPack 5.0.2. It should be released within weeks if all goes according to schedule.

Thanks,
Cody
