### ISSUE TITLE
White pixel line

### ISSUE THREAD

**Issue by g-towboat** [D3Engineering/d3-jetson-bsp#4]
We have a pixel line in our images.
What is it ? Or what are we doing wrong?

![image003](https://user-images.githubusercontent.com/42449688/73835978-a567b280-480e-11ea-9f1e-49553947bcef.png)

**Comment by D3-growe** [comment]
You aren't doing anything wrong, this is normal.

The Sony imx390 sensor produces 4 SMPG lines at the bottom of each frame. SMPG stands for "Safety Mechanism Pattern Generator". There is no documented way to disable these lines at the sensor according to my contacts at Sony.

I recommend cropping these lines out.
