### ISSUE TITLE
Yocto support for D3

### ISSUE THREAD

**Issue by RomainNaour** [D3Engineering/d3-jetson-bsp#9]
Hello,

It would be great if you can provide D3 kernel sources for Yocto.

What about working on top of linux-tegra-4.9 from OE4T ?
This kernel is actively maintained for Tegra CPU and Nvidia stack.
The OE4T maintainer merged the nvidia sources into the kernel repository in order to build the kernel into Yocto kernel recipe [1].

I used the same method with D3 sources but it's a difficult maintenance on our side...

[1] https://github.com/OE4T/linux-tegra-4.9/commits/oe4t-patches-l4t-r32.4?after=87e09c14b15ad302b451f40f4237bb14f553c1e0+69&branch=oe4t-patches-l4t-r32.4

Best regards,
Romain

**Comment by D3-growe** [comment]
Hi Romain,

Thank you for the suggestion. Yocto is indeed very interesting. 

Thanks,
Greg
